### PR TITLE
Document planned features

### PR DESCRIPTION
**Pull request by Timoses**
Also provides a config file for readthedocs

### CODE REVIEW

**Comment by LexiconCode** [comment]
It'll be easier to coordinate if you mark your PR as WIP before you submit it. That way I can merge if I feel that it's ready without confirming if it's complete.

**Comment by Timoses** [comment]
I'd like to update the links to point to the correct repo.. Currently the documentation links to Timoses/Caster .

All open issues from https://github.com/Timoses/Caster/issues are relevant to this repository, I think. Can you move them here?

**Comment by LexiconCode** [comment]
> 
> 
> I'd like to update the links to point to the correct repo.. Currently the documentation links to Timoses/Caster .
> 
> All open issues from [https://github.com/Timoses/Caster/issues](https://github.com/Timoses/Caster/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) are relevant to this repository, I think. Can you move them here?

It's not giving me that option to this repository to transfer, I assume that the same issue for you. Worst case we will have to repost.

**Comment by Timoses** [comment]
> > I'd like to update the links to point to the correct repo.. Currently the documentation links to Timoses/Caster .
> > All open issues from [https://github.com/Timoses/Caster/issues](https://github.com/Timoses/Caster/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) are relevant to this repository, I think. Can you move them here?
> 
> It's not giving me that option to this repository to transfer, I assume that the same issue for you. Worst case we will have to repost.

https://docs.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository
states "You can only transfer issues between repositories owned by the same user or organization account.You can't transfer an issue from a private repository to a public repository." Can we make this work somehow?
I can transfer ownership to a user or organization. Is `CasterVoice` the organization?

**Comment by LexiconCode** [comment]
CasterVoice is an organization. I'm not sure what it means to have a fork that belongs to another organization such as the dictation toolbox in the transfer that fork to a different organization but I guess we'll find out.

So let's give it a shot and it can be a temporary arrangement after the issues are transferred.

**Comment by Timoses** [comment]
> So let's give it a shot and it can be a temporary arrangement after the issues are transferred.

Done. Imo all open issues are suitable for transfer.

**Comment by LexiconCode** [comment]
> 
> 
> > So let's give it a shot and it can be a temporary arrangement after the issues are transferred.
> 
> Done. Imo all open issues are suitable for transfer.

I changed the your role to Admin you can transfer the repository to your user account. There's limitations transferring repositories from an organization to other individuals besides oneself. See the error message below:

> You can only transfer a repository from an organization to yourself at this time

**Comment by Timoses** [comment]
> I changed the your role to Admin you can transfer the Caster repository to your user account. There's limitations transferring repositories from an organization to other individuals besides oneself.

Seems like you managed after all : ).

I exchanged the links. Should be good to go now.

**Pull request merged**
